
project_id = "crisbuthezpbojcshrwh"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true

[analytics]
enabled = false

[functions.generate-notebook-content]
verify_jwt = true

[functions.send-chat-message]
verify_jwt = true

[functions.chat-handler]
enabled = true
verify_jwt = false
import_map = "./functions/chat-handler/deno.json"
entrypoint = "./functions/chat-handler/index.ts"

[functions.process-document]
verify_jwt = true

[functions.process-document-callback]
verify_jwt = false

[functions.process-additional-sources]
verify_jwt = true

[functions.get-analysis-results]
enabled = true
verify_jwt = true
import_map = "./functions/get-analysis-results/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-analysis-results/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-analysis-results/*.html" ]

[functions.update-profile]
enabled = true
verify_jwt = true
import_map = "./functions/update-profile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-profile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-profile/*.html" ]

[functions.generate-upload-url]
enabled = true
verify_jwt = true
import_map = "./functions/generate-upload-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-upload-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-upload-url/*.html" ]

[functions.upload-to-backblaze]
enabled = true
verify_jwt = false
import_map = "./functions/upload-to-backblaze/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-to-backblaze/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-to-backblaze/*.html" ]
